#!/usr/bin/env python3
"""Fail if the repo references an asset path that isn't in asset_tree.txt.

asset_tree.txt is generated by scripts/publish/publish_assets.ts at pack-build
time — it's the authoritative list of every non-kenney asset that ships in the
universal .pck. If a dev adds `res://assets/enemies/rappy/rappy.glb` in code but
doesn't re-publish the pack, CI catches it here and tells them what to do.

Kenney subdirs (`assets/kenney_*`) ship in-repo with the main exe, so references
to them are fine regardless of asset_tree.txt.
"""

from __future__ import annotations
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
ASSET_TREE = REPO_ROOT / "asset_tree.txt"
IGNORE_FILE = Path(__file__).resolve().parent / "asset_refs_ignore.txt"

# Match res://assets/... paths inside string literals. Handles both "..." and
# '...' quoting; stops at the closing quote or at whitespace. Excludes the
# trailing `.import` suffix: Godot .tscn files reference sources (e.g.
# `res://assets/foo.glb`), while `.glb.import` sidecars are runtime bookkeeping.
PATH_RE = re.compile(r'res://(assets/[^"\'\s\)]+)')

# Extensions we scan for asset references. Keep this narrow — we want code +
# scene files, not godot-internal bookkeeping like .import or .uid sidecars.
SCAN_SUFFIXES = {".gd", ".tscn", ".tres", ".cs"}

# Directories that never ship in the asset pack (referenced paths here are OK).
# assets/ui/ holds small UI sprites committed directly to the repo.
# assets/animations/ holds reverse-retargeted VRMA clips that ride with the
# binary instead of the pack (see the matching gitignore comment) — output
# of web/scripts/bake-vrma-to-psz.mjs.
IN_REPO_PREFIXES = ("assets/kenney_", "assets/ui/", "assets/animations/")


def load_ignore() -> set[str]:
    if not IGNORE_FILE.exists():
        return set()
    out: set[str] = set()
    for line in IGNORE_FILE.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            out.add(line)
    return out


def load_asset_tree() -> set[str]:
    if not ASSET_TREE.exists():
        print(f"::error::{ASSET_TREE} missing — run `npm run upload-pack` to generate it.")
        sys.exit(2)
    return {line.strip() for line in ASSET_TREE.read_text().splitlines() if line.strip()}


def find_references() -> dict[str, list[str]]:
    """Return {asset_path: [referencing_file, ...]}."""
    refs: dict[str, list[str]] = {}
    for path in REPO_ROOT.rglob("*"):
        # Skip common noise early; walking the tree is the bottleneck.
        if path.is_dir():
            continue
        if path.suffix not in SCAN_SUFFIXES:
            continue
        if any(p.startswith(".") for p in path.relative_to(REPO_ROOT).parts):
            continue
        parts = path.relative_to(REPO_ROOT).parts
        if parts[0] in ("build", "dist", "node_modules", ".godot"):
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        for m in PATH_RE.finditer(text):
            asset_path = m.group(1)
            refs.setdefault(asset_path, []).append(str(path.relative_to(REPO_ROOT)))
    return refs


def main() -> int:
    tree = load_asset_tree()
    ignore = load_ignore()
    refs = find_references()

    missing: list[tuple[str, list[str]]] = []
    for asset_path, sources in sorted(refs.items()):
        if any(asset_path.startswith(p) for p in IN_REPO_PREFIXES):
            continue
        if asset_path in ignore:
            continue
        # Format-string templates (`res://assets/stages/%s/...`) and glob
        # patterns (`res://assets/sfx/weapons/saber_swing_*.wav`) are resolved
        # at runtime — we can't verify them statically here.
        if "%" in asset_path or "*" in asset_path:
            continue
        # asset_tree.txt lists source files (e.g. `assets/enemies/rappy/rappy.glb`);
        # code usually references the source too, but sometimes references
        # .import-derived paths or specific textures. Accept a hit if ANY prefix
        # of the referenced path matches a listed file.
        if asset_path in tree:
            continue
        # Also accept if the reference points *inside* a listed directory that
        # we happen to have indexed — e.g. code writes `res://assets/stages/foo/`
        # for a directory scan.
        if any(listed.startswith(asset_path) for listed in tree):
            continue
        missing.append((asset_path, sources))

    if not missing:
        print(f"ok: all {len(refs)} asset references resolve in asset_tree.txt")
        return 0

    print("::error::Assets referenced in code but not in the published pack:")
    print()
    for asset_path, sources in missing:
        print(f"  res://{asset_path}")
        for src in sources[:3]:
            print(f"    referenced by {src}")
        if len(sources) > 3:
            print(f"    ... and {len(sources) - 3} more")
        print()
    print("Fix: run `cd scripts/publish && npm run upload-pack` on your dev")
    print("machine, then commit the updated assets_manifest.json + asset_tree.txt.")
    return 1


if __name__ == "__main__":
    sys.exit(main())
