extends SceneTree
## Dump generated free fields to JSON for the web grid viewer (#/field-generator).
##
## The viewer renders THIS output rather than re-implementing the generator in
## TypeScript. A second implementation would drift from GridGenerator, and then
## the thing being eyeballed would not be the thing the game ships — which is
## the opposite of what a fidelity check is for.
##
## Every field is dumped with the seed that produced it, so a layout that looks
## wrong in the browser can be reproduced exactly in Godot (GridGenerator.set_seed)
## and, once psz-re can dump the real game's fields for a known seed, compared
## against it directly.
##
## Run:
##   godot --headless --path . --script res://scripts/tools/dump_generated_fields.gd
## Writes web/public/field-dumps/generated-fields.json

const GG := preload("res://scripts/3d/field/grid_generator.gd")
## web/public/data is a SYMLINK to the repo's data/ directory, which ships in
## the asset pack — writing a web artefact there would pollute game data. Use a
## real directory under web/public instead.
const OUT_PATH := "res://web/public/field-dumps/generated-fields.json"
const AREAS := ["gurhacia", "ozette", "rioh", "makara", "paru", "arca", "dark"]
## Seeds per area. Fixed so the committed dump is stable and a reviewer sees the
## same grids the author did; bump to resample.
const SEEDS := [1, 2, 3, 4]
const DIFFICULTY := "normal"


func _init() -> void:
	var areas: Array = []
	for area_id in AREAS:
		var rolls: Array = []
		for seed_value in SEEDS:
			var gen = GG.new()
			gen.set_seed(seed_value)
			var field: Dictionary = gen.generate_field(DIFFICULTY, area_id)
			rolls.append({
				"seed": seed_value,
				"sections": field["sections"],
			})
		areas.append({
			"area_id": area_id,
			"display_name": str(GG.AREA_CONFIG.get(area_id, {}).get("name", area_id)),
			"prefix": str(GG.AREA_CONFIG.get(area_id, {}).get("prefix", "")),
			"rolls": rolls,
		})

	var doc := {
		"_comment": (
			"Generated by scripts/tools/dump_generated_fields.gd from GridGenerator — "
			+ "do not hand-edit. Re-run the dumper after changing the generator. "
			+ "Each roll records the seed that produced it; GridGenerator.set_seed(seed) "
			+ "reproduces the same field in-engine."
		),
		"difficulty": DIFFICULTY,
		"grid_size": GG.load_grid_size(),
		"areas": areas,
	}

	var dir_path := OUT_PATH.get_base_dir()
	if not DirAccess.dir_exists_absolute(ProjectSettings.globalize_path(dir_path)):
		DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(dir_path))
	var out := FileAccess.open(OUT_PATH, FileAccess.WRITE)
	if not out:
		print("FAILED to open ", OUT_PATH)
		quit(1)
		return
	out.store_string(JSON.stringify(doc, "  "))
	out.close()

	var cells := 0
	for a in areas:
		for r in a["rolls"]:
			for sec in r["sections"]:
				cells += sec["cells"].size()
	print("wrote %s — %d areas x %d seeds, %d cells" % [OUT_PATH, AREAS.size(), SEEDS.size(), cells])
	quit()
