#!/usr/bin/env python3
"""Vendor psz-re's findings into web/public so the field preview can cite them.

The preview marks every value as measured / inferred / ours
(web/src/field-generator/provenance.ts). That tells you WHAT we believe; this
brings across WHY — psz-re's own summary, confidence and evidence for each
finding, so a claim in the tool can be traced to the thing that established it
rather than to a sentence one of us wrote from memory.

    python3 scripts/tools/refield/sync_re_references.py           # write
    python3 scripts/tools/refield/sync_re_references.py --check   # drift guard

Skips cleanly (exit 0) when psz-re is not checked out, like import_re_objects.
Point it with --psz-re or $PSZ_RE.

WHY A COPY RATHER THAN A FETCH. psz-re is a separate repo on a different
machine; the web build has no access to it, and the tool must work from a fresh
clone with no network. So the summaries are vendored, deliberately small, and
regenerated by this script. The trade is that they can go stale — which is what
`--check` is for, and why every entry carries the source path and psz-re's own
confidence rather than being paraphrased here.

ONLY THE PROSE IS COPIED. Not the addresses, not the raw evidence blobs: the
tool needs a human-readable claim and a pointer, and psz-re's files are the
place to go for the rest.
"""
from __future__ import annotations

import argparse
import json
import os
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent.parent.parent
OUT = ROOT / "web" / "public" / "data" / "re-references.json"

# The findings the field preview actually shows. Each entry names a psz-re file
# and how to pull a claim out of it, because the two shapes differ: `nodes/*`
# carry summary + confidence, while `data/*` carry topic keys we quote directly.
NODES = [
    ("sys.field-doorways", "nodes/sys.field-doorways.json",
     "doors == connections; there is never a spare door"),
    ("fmt.room-object-set", "nodes/fmt.room-object-set.json",
     "the authored per-room object table behind boxes, gates and traps"),
]

DATA_TOPICS = [
    ("gate economy", "data/level_topology_builder.json",
     ["key_gate_budget", "one_key_versus_two", "enemy_defeat_gates",
      "door_attributes", "gate_and_key_placement"]),
    ("layout selection", "data/level_generation_algorithm.json",
     ["field_0x31_identified"]),
]

MAX_SUMMARY = 1200


def psz_re_root(explicit: str | None) -> pathlib.Path | None:
    for candidate in (explicit, os.environ.get("PSZ_RE"),
                      str(ROOT.parent.parent / "psz-re"),
                      str(ROOT.parent / "psz-re")):
        if not candidate:
            continue
        p = pathlib.Path(candidate).expanduser()
        if (p / "nodes").is_dir() or (p / "data").is_dir():
            return p
    return None


def build(re_root: pathlib.Path) -> dict:
    refs: list[dict] = []

    for key, rel, blurb in NODES:
        path = re_root / rel
        if not path.exists():
            continue
        node = json.loads(path.read_text())
        refs.append({
            "id": key,
            "title": str(node.get("label", key)),
            "blurb": blurb,
            "confidence": str(node.get("confidence", "unknown")),
            "summary": str(node.get("summary", ""))[:MAX_SUMMARY],
            "source": rel,
            "open_questions": node.get("open_questions", [])[:3],
        })

    for key, rel, topics in DATA_TOPICS:
        path = re_root / rel
        if not path.exists():
            continue
        doc = json.loads(path.read_text())
        for topic in topics:
            if topic not in doc:
                continue
            refs.append({
                "id": "%s/%s" % (key, topic),
                "title": topic.replace("_", " "),
                "blurb": key,
                "confidence": "documented",
                "summary": json.dumps(doc[topic], ensure_ascii=False)[:MAX_SUMMARY],
                "source": "%s#%s" % (rel, topic),
                "open_questions": [],
            })

    return {
        "_": ("psz-re findings vendored for the field preview. Regenerate with "
              "scripts/tools/refield/sync_re_references.py — do not hand-edit, "
              "the point is that these are psz-re's words and not ours."),
        "references": refs,
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--psz-re")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    re_root = psz_re_root(args.psz_re)
    if re_root is None:
        print("psz-re not found (pass --psz-re or set $PSZ_RE) -- skipping")
        return 0

    doc = build(re_root)
    text = json.dumps(doc, indent=2, ensure_ascii=False) + "\n"

    if args.check:
        if not OUT.exists():
            print("FAIL: %s missing -- run without --check" % OUT.relative_to(ROOT))
            return 1
        if OUT.read_text() != text:
            print("FAIL: %s is stale against psz-re -- re-run this script"
                  % OUT.relative_to(ROOT))
            return 1
        print("ok: %s matches psz-re (%d references)"
              % (OUT.relative_to(ROOT), len(doc["references"])))
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print("wrote %s (%d references)" % (OUT.relative_to(ROOT), len(doc["references"])))
    for r in doc["references"]:
        print("  %-28s %s" % (r["id"], r["confidence"]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
