import { useEffect, useMemo, useState } from 'react';
import { assetUrl } from '../../utils/assets';
import { KIND_COLOR, type AuthoredObject } from '../AuthoredObjectOverlay';
import { layoutEligibility, layoutShares, maskGroups } from '../layoutMasks';

/**
 * What the ORIGINAL authors into this room — the measured side of the field
 * generator, listed so it can be checked against the geometry in the viewport.
 *
 * The point of this tab is sanity-checking a definition, not editing one:
 * everything here comes from psz-re and is regenerated by
 * scripts/tools/refield/import_re_objects.py. Editing belongs upstream.
 */

interface Props {
  stageId: string;
  visibleKinds: string[] | null;
  setVisibleKinds: (kinds: string[] | null) => void;
  /** null = the whole table; a mask value previews that layout's outcome. */
  layoutMask: number | null;
  setLayoutMask: (mask: number | null) => void;
  /** Group 5's rolled count (0–3) while a layout is selected. */
  group5Count: number;
  setGroup5Count: (n: number) => void;
  /** Draw the storybook model for kinds that have one, instead of markers. */
  realModels: boolean;
  setRealModels: (on: boolean) => void;
}

interface RoomEntry {
  groups?: number[] | null;
  objects: AuthoredObject[];
}

/** The weight rows room_objects.json publishes, in display order. */
const DEPTH_BANDS = ['lt4', '4_6', 'ge7'] as const;

export default function AuthoredTab({
  stageId,
  visibleKinds,
  setVisibleKinds,
  layoutMask,
  setLayoutMask,
  group5Count,
  setGroup5Count,
  realModels,
  setRealModels,
}: Props) {
  const [rooms, setRooms] = useState<Record<string, RoomEntry> | null>(null);
  // The mask/weight constants travel with the data (same file as rooms).
  const [masks, setMasks] = useState<number[]>([]);
  const [weightsByDepth, setWeightsByDepth] = useState<Record<string, number[]>>({});
  const [group5Weights, setGroup5Weights] = useState<number[]>([]);
  const [reference, setReference] = useState<Record<string, {
    objects?: { k: string }[];
    enemies?: unknown[];
    blocks?: number;
    flags?: number[];
  }> | null>(null);

  useEffect(() => {
    fetch(assetUrl('/data/re_reference/room_objects.json'))
      .then((r) => (r.ok ? r.json() : null))
      .then((d) => {
        setRooms(d?.rooms ?? null);
        setMasks(d?.layout_masks ?? []);
        setWeightsByDepth(d?.layout_weights_by_depth ?? {});
        setGroup5Weights(d?.group5_weights ?? []);
      })
      .catch(() => setRooms(null));
    fetch(assetUrl('/data/re_reference/room_reference.json'))
      .then((r) => (r.ok ? r.json() : null))
      .then((d) => setReference(d?.rooms ?? null))
      .catch(() => setReference(null));
  }, []);

  const entry = rooms?.[`${stageId}_d`];
  const byKind = useMemo(() => {
    const out: Record<string, number> = {};
    for (const o of entry?.objects ?? []) out[o.k] = (out[o.k] ?? 0) + 1;
    return out;
  }, [entry]);

  const byGroup = useMemo(() => {
    const out: Record<string, number> = {};
    for (const o of entry?.objects ?? []) {
      const g = o.g === null || o.g === undefined ? 'ungrouped' : String(o.g);
      out[g] = (out[g] ?? 0) + 1;
    }
    return out;
  }, [entry]);

  const kinds = Object.keys(byKind).sort();

  // The room's real variations: eligibility comes from the measured group
  // table (which can name groups the importer did not emit), and each band's
  // row gives the share of visits per layout after _pick_layout's fallback.
  const eligible =
    entry?.groups != null && masks.length > 0 ? layoutEligibility(entry.groups, masks) : [];
  const sharesByBand = DEPTH_BANDS.map((b) => layoutShares(masks, eligible, weightsByDepth[b] ?? []));
  // A layout is previewable if the room can draw it — or, when no mask is
  // eligible at all, if it is layout 0, the draw's terminal fallback.
  const previewable = (i: number) =>
    eligible[i] || sharesByBand.some((shares) => (shares[i] ?? 0) > 0);
  const group5Total = (entry?.objects ?? []).filter((o) => o.g === 5).length;

  // The reference layer: what the original has here that we do not place.
  const ref = reference?.[`${stageId}_d`];
  const refByKind: Record<string, number> = {};
  for (const o of ref?.objects ?? []) refByKind[o.k] = (refByKind[o.k] ?? 0) + 1;
  const spawnCount = ref?.enemies?.length ?? 0;
  if (spawnCount) refByKind['enemy spawn'] = spawnCount;
  const refKinds = Object.keys(refByKind).sort();

  return (
    <div style={{ padding: 16, color: '#e8e8f0', fontSize: 13, lineHeight: 1.5 }}>
      <h3 style={{ margin: '0 0 4px' }}>Authored objects</h3>
      <div style={{ color: '#8a90b8', fontSize: 11, marginBottom: 12 }}>
        Measured, from psz-re's per-room object table. Room-local coordinates in
        the same frame as the doorways, plus a 16-bit facing. Read-only — this is
        the original's data, regenerated by <code>import_re_objects.py</code>.
      </div>

      {!rooms && <div style={{ color: '#8a90b8' }}>Loading…</div>}
      {rooms && !entry && (
        <div style={{ color: '#e0c97a' }}>
          No authored objects for <code>{stageId}_d</code>. City stages and a few
          field rooms carry none in set <code>d</code>.
        </div>
      )}

      {entry && (
        <>
          {/* Marker vs storybook-model rendering for the viewport. */}
          <div style={{ marginBottom: 12 }}>
            {(['markers', 'models'] as const).map((mode) => {
              const on = mode === 'models' ? realModels : !realModels;
              return (
                <button
                  key={mode}
                  onClick={() => setRealModels(mode === 'models')}
                  style={{
                    background: on ? '#2a2a4a' : '#12122a',
                    color: '#e8e8f0',
                    border: `1px solid ${on ? '#4a9eff' : '#2a2a4a'}`,
                    borderRadius: 4,
                    padding: '3px 8px',
                    fontSize: 11,
                    cursor: 'pointer',
                    margin: '0 6px 6px 0',
                  }}
                  title={
                    mode === 'models'
                      ? 'Draw the storybook model for kinds that have one — containers, walls, fences, switches, needler/gun/poison traps, at true scale. The other trap families have no identified model and stay as discs.'
                      : 'Coloured primitives — the lightweight default.'
                  }
                >
                  {mode}
                </button>
              );
            })}
            {realModels && (
              <div style={{ fontSize: 11, color: '#8a90b8', marginTop: 4 }}>
                Models load on first use and fall back to markers if one fails.
                Boxes and walls use this field's own art. burn / capture / heal
                / heat / light / ice traps have no identified model yet and stay
                as discs.
              </div>
            )}
          </div>

          <div style={{ marginBottom: 12 }}>
            <strong>{entry.objects.length}</strong> objects
            {entry.groups && (
              <span
                style={{ color: '#8a90b8' }}
                title="The original's group-size table; the imported objects below can be a subset of it (unhandled kinds are not emitted)."
              >
                {' '}· group sizes [{entry.groups.join(', ')}]
              </span>
            )}
          </div>

          {/* A room never builds all of this at once, and the group is the only
              thing that says which subset arrives together. */}
          <div style={{ marginBottom: 12, fontSize: 11, color: '#8a90b8' }}>
            by group:{' '}
            {Object.entries(byGroup)
              .sort()
              .map(([g, n]) => `${g}:${n}`)
              .join('  ')}
            <div style={{ marginTop: 4 }}>
              A visit builds a subset of the table — pick a layout below to
              render one real arrangement instead of every record at once.
            </div>
          </div>

          {entry.groups == null ? (
            <div style={{ marginBottom: 12, fontSize: 11, color: '#8a90b8' }}>
              No recoverable group table for this room — the original builds
              the file flat, so it has no variations to preview.
            </div>
          ) : (
            masks.length > 0 && (
              <>
                <div style={{ marginBottom: 4, fontSize: 11, color: '#8a90b8' }}>
                  layout preview — draw % by tree depth &lt;4 · 4–6 · ≥7,
                  eligibility fallback included:
                </div>
                <div style={{ marginBottom: 8 }}>
                  <button
                    onClick={() => setLayoutMask(null)}
                    style={{
                      background: layoutMask === null ? '#2a2a4a' : '#12122a',
                      color: '#e8e8f0',
                      border: `1px solid ${layoutMask === null ? '#4a9eff' : '#2a2a4a'}`,
                      borderRadius: 4,
                      padding: '3px 8px',
                      fontSize: 11,
                      cursor: 'pointer',
                      margin: '0 6px 6px 0',
                    }}
                    title="Every record in the file, no mask applied — the table, not a single visit."
                  >
                    table
                  </button>
                  {masks.map((m, i) => {
                    const selected = layoutMask === m;
                    const on = previewable(i);
                    const built = maskGroups(m);
                    const bandShares = sharesByBand.map((s) => s[i] ?? 0);
                    const never = i === 4;
                    const face =
                      bandShares.some((s) => s > 0)
                        ? `L${i} g${built.join('+')} · ${bandShares.join('·')}`
                        : never
                          ? `L${i} g${built.join('+')} · never drawn`
                          : `L${i} g${built.join('+')} · —`;
                    const title = !on
                      ? `mask ${m} names an empty group for this room — never drawn`
                      : never
                        ? `mask ${m} → groups ${built.join(', ')} + the group-5 roll. Never drawn: the original's layout draw returns 0..3 by design — group 4's objects never spawn in a free field.`
                        : `mask ${m} → groups ${built.join(', ')} + the group-5 roll. Draw % for depth <4 / 4–6 / ≥7: ${bandShares.join(' / ')}`;
                    return (
                      <button
                        key={m}
                        disabled={!on}
                        onClick={() => setLayoutMask(m)}
                        style={{
                          background: selected ? '#2a2a4a' : '#12122a',
                          color: on ? '#e8e8f0' : '#555',
                          border: `1px solid ${selected ? '#4a9eff' : '#2a2a4a'}`,
                          borderRadius: 4,
                          padding: '3px 8px',
                          fontSize: 11,
                          cursor: on ? 'pointer' : 'not-allowed',
                          margin: '0 6px 6px 0',
                        }}
                        title={title}
                      >
                        {face}
                      </button>
                    );
                  })}
                </div>
                {layoutMask != null && group5Total > 0 && (
                  <div style={{ marginBottom: 12, fontSize: 11, color: '#8a90b8' }}>
                    group-5 roll ({(group5Weights.length ? group5Weights : [40, 20, 20, 20]).join('/')} → count 0–
                    {Math.min(3, group5Total)}):{' '}
                    {Array.from({ length: Math.min(3, group5Total) + 1 }, (_, n) => (
                      <button
                        key={n}
                        onClick={() => setGroup5Count(n)}
                        style={{
                          background: group5Count === n ? '#2a2a4a' : '#12122a',
                          color: '#e8e8f0',
                          border: `1px solid ${group5Count === n ? '#4a9eff' : '#2a2a4a'}`,
                          borderRadius: 4,
                          padding: '3px 8px',
                          fontSize: 11,
                          cursor: 'pointer',
                          margin: '0 6px 6px 0',
                        }}
                        title={`rolled count ${n}${
                          group5Weights[n] !== undefined ? ` — ${group5Weights[n]}% of visits` : ''
                        }`}
                      >
                        {n}
                      </button>
                    ))}
                    <div style={{ marginTop: 4 }}>
                      {group5Count === 0
                        ? `Nothing from group 5 — ${group5Weights[0] ?? 40}% of visits roll this.`
                        : `Shown take is the first ${group5Count} in table order — the game shuffles the group, so WHICH ${group5Count} varies per visit.`}
                    </div>
                  </div>
                )}
              </>
            )
          )}

          <div style={{ marginBottom: 8 }}>
            <button
              onClick={() => setVisibleKinds(null)}
              style={{
                background: visibleKinds === null ? '#2a2a4a' : '#12122a',
                color: '#e8e8f0',
                border: '1px solid #2a2a4a',
                borderRadius: 4,
                padding: '3px 8px',
                fontSize: 11,
                cursor: 'pointer',
                marginRight: 6,
              }}
            >
              show all
            </button>
            {kinds.map((k) => {
              const on = visibleKinds === null || visibleKinds.includes(k);
              return (
                <button
                  key={k}
                  onClick={() =>
                    setVisibleKinds(
                      visibleKinds === null
                        ? kinds.filter((x) => x !== k)
                        : on
                          ? visibleKinds.filter((x) => x !== k)
                          : [...visibleKinds, k],
                    )
                  }
                  style={{
                    background: on ? '#1a1a2e' : '#0f0f1e',
                    color: on ? KIND_COLOR[k] ?? '#e8e8f0' : '#555',
                    border: `1px solid ${on ? KIND_COLOR[k] ?? '#2a2a4a' : '#2a2a4a'}`,
                    borderRadius: 4,
                    padding: '3px 8px',
                    fontSize: 11,
                    cursor: 'pointer',
                    margin: '0 6px 6px 0',
                  }}
                >
                  {k} {byKind[k]}
                </button>
              );
            })}
          </div>
        </>
      )}

      {refKinds.length > 0 && (
        <div style={{ marginTop: 18, borderTop: '1px solid #2a2a4a', paddingTop: 12 }}>
          <strong style={{ color: '#f87171' }}>What we do NOT place</strong>
          <div style={{ color: '#8a90b8', fontSize: 11, margin: '4px 0 8px' }}>
            Drawn as open wireframe so it never reads as something the game
            builds. Keys are authored per room in the original — psz-godot
            scatters them by rule instead — and enemy spawn slots are measured
            while we still ring enemies at radius 5.0 (psz-godot#604).
            {ref?.blocks !== undefined && (
              <div style={{ marginTop: 4 }}>
                deploy blocks: {ref.blocks} · flags [{(ref.flags ?? []).join(', ')}]
                {' '}— 254 of 257 rooms have one block, so a block is not a wave;
                the flag is only ever 0 or 1 and nobody knows what it means yet.
              </div>
            )}
          </div>
          {refKinds.map((k) => {
            const on = visibleKinds === null || visibleKinds.includes(k);
            return (
              <button
                key={k}
                onClick={() =>
                  setVisibleKinds(
                    visibleKinds === null
                      ? [...kinds, ...refKinds].filter((x) => x !== k)
                      : on
                        ? visibleKinds.filter((x) => x !== k)
                        : [...visibleKinds, k],
                  )
                }
                style={{
                  background: on ? '#1a1a2e' : '#0f0f1e',
                  color: on ? (k === 'key' ? '#ffd166' : k === 'enemy spawn' ? '#f87171' : '#9aa') : '#555',
                  border: '1px dashed #3a3a5a',
                  borderRadius: 4,
                  padding: '3px 8px',
                  fontSize: 11,
                  cursor: 'pointer',
                  margin: '0 6px 6px 0',
                }}
              >
                {k} {refByKind[k]}
              </button>
            );
          })}
        </div>
      )}
    </div>
  );
}
