import { useEffect, useMemo, useState, type CSSProperties } from 'react';
import { assetUrl } from '../../utils/assets';
import { KIND_COLOR, type AuthoredObject } from '../AuthoredObjectOverlay';
import { layoutEligibility, layoutShares, maskGroups, pickDefaultLayout } from '../layoutMasks';

/**
 * What the ORIGINAL authors into this room — the measured side of the field
 * generator. The panel leads with the LAYOUTS list (a room's real
 * arrangements) because that is the question this tab answers; the prose
 * that used to explain all this lives behind tooltips on the controls
 * themselves.
 *
 * Everything here comes from psz-re and is regenerated by
 * scripts/tools/refield/import_re_objects.py. Read-only — editing belongs
 * upstream.
 */

interface Props {
  stageId: string;
  visibleKinds: string[] | null;
  setVisibleKinds: (kinds: string[] | null) => void;
  layoutMask: number | null;
  setLayoutMask: (mask: number | null) => void;
  /** Group 5's rolled count (0–3) while a layout is selected. */
  group5Count: number;
  setGroup5Count: (n: number) => void;
}

interface RoomEntry {
  groups?: number[] | null;
  objects: AuthoredObject[];
}

/** The weight rows room_objects.json publishes; the mid band is the one the
 * button faces quote, the tooltip carries all three. */
const DEPTH_BANDS = ['lt4', '4_6', 'ge7'] as const;
const FACE_BAND = '4_6';

const sectionLabel: CSSProperties = {
  fontSize: 11,
  color: '#8a90b8',
  textTransform: 'uppercase',
  letterSpacing: 1,
  margin: '14px 0 6px',
};

function chipStyle(on: boolean, borderColor?: string): CSSProperties {
  return {
    background: on ? '#2a2a4a' : '#12122a',
    color: '#e8e8f0',
    border: `1px solid ${on ? borderColor ?? '#4a9eff' : '#2a2a4a'}`,
    borderRadius: 4,
    padding: '3px 8px',
    fontSize: 11,
    cursor: 'pointer',
    margin: '0 6px 6px 0',
  };
}

export default function AuthoredTab({
  stageId,
  visibleKinds,
  setVisibleKinds,
  layoutMask,
  setLayoutMask,
  group5Count,
  setGroup5Count,
}: Props) {
  const [rooms, setRooms] = useState<Record<string, RoomEntry> | null>(null);
  // The mask/weight constants travel with the data (same file as rooms).
  const [masks, setMasks] = useState<number[]>([]);
  const [weightsByDepth, setWeightsByDepth] = useState<Record<string, number[]>>({});
  const [group5Weights, setGroup5Weights] = useState<number[]>([]);
  const [reference, setReference] = useState<Record<string, {
    objects?: { k: string }[];
    enemies?: unknown[];
    blocks?: number;
    flags?: number[];
  }> | null>(null);

  useEffect(() => {
    fetch(assetUrl('/data/re_reference/room_objects.json'))
      .then((r) => (r.ok ? r.json() : null))
      .then((d) => {
        setRooms(d?.rooms ?? null);
        setMasks(d?.layout_masks ?? []);
        setWeightsByDepth(d?.layout_weights_by_depth ?? {});
        setGroup5Weights(d?.group5_weights ?? []);
      })
      .catch(() => setRooms(null));
    fetch(assetUrl('/data/re_reference/room_reference.json'))
      .then((r) => (r.ok ? r.json() : null))
      .then((d) => setReference(d?.rooms ?? null))
      .catch(() => setReference(null));
  }, []);

  const entry = rooms?.[`${stageId}_d`];
  const byKind = useMemo(() => {
    const out: Record<string, number> = {};
    for (const o of entry?.objects ?? []) out[o.k] = (out[o.k] ?? 0) + 1;
    return out;
  }, [entry]);
  const kinds = Object.keys(byKind).sort();

  // Eligibility comes from the measured group table (which can name groups
  // the importer did not emit); each band's row gives the share of visits per
  // layout after _pick_layout's fallback.
  const eligible =
    entry?.groups != null && masks.length > 0 ? layoutEligibility(entry.groups, masks) : [];
  const sharesByBand = DEPTH_BANDS.map((b) => layoutShares(masks, eligible, weightsByDepth[b] ?? []));
  const faceShares = sharesByBand[DEPTH_BANDS.indexOf(FACE_BAND)];
  const group5Total = (entry?.objects ?? []).filter((o) => o.g === 5).length;

  // A room with no explicit pick opens on its most-taken arrangement.
  useEffect(() => {
    if (layoutMask != null) return;
    if (entry?.groups == null || masks.length === 0) return;
    const pick = pickDefaultLayout(masks, eligible, weightsByDepth[FACE_BAND] ?? []);
    setLayoutMask(masks[pick]);
  }, [layoutMask, entry, masks, eligible, weightsByDepth, setLayoutMask]);

  // The reference layer: keys, treasure boxes, unidentified kinds, and the
  // wave's spawn slots. All of it is INDEPENDENT of the room's layout — keys
  // exist regardless of the drawn mask (field_population.key_slot_positions
  // prefers in-mask slots and falls back to all; which rooms hold keys is the
  // gate economy's decision), spawns belong to the wave — so it renders above
  // the layouts, unfiltered by the selected mask.
  const ref = reference?.[`${stageId}_d`];
  const refByKind: Record<string, number> = {};
  for (const o of ref?.objects ?? []) refByKind[o.k] = (refByKind[o.k] ?? 0) + 1;
  const spawnCount = ref?.enemies?.length ?? 0;
  if (spawnCount) refByKind['enemy spawn'] = spawnCount;
  const refKinds = Object.keys(refByKind).sort();

  return (
    <div style={{ padding: 16, color: '#e8e8f0', fontSize: 13, lineHeight: 1.5 }}>
      <h3
        style={{ margin: '0 0 8px' }}
        title="Measured from psz-re's per-room object table (set/<NN>/<v>/<room>/*.rel), room-local coordinates in the doorway frame, plus a 16-bit facing. Read-only — regenerated by import_re_objects.py; editing belongs upstream."
      >
        Authored objects
      </h3>

      {!rooms && <div style={{ color: '#8a90b8' }}>Loading…</div>}
      {rooms && !entry && (
        <div style={{ color: '#e0c97a', fontSize: 12 }}>
          No authored objects for <code>{stageId}_d</code> — city stages and a
          few field rooms carry none in set <code>d</code>.
        </div>
      )}

      {entry && (
        <>
          {refKinds.length > 0 && (
            <>
              <div
                style={sectionLabel}
                title="Independent of the room's layout: which rooms hold keys is the gate economy's decision — the game prefers slots in the drawn layout and falls back to all of them (field_population.key_slot_positions); enemy slots belong to the room's wave; treasure boxes and unidentified kinds are measured but not placed. Drawn as open wireframe, floor-snapped to the stage mesh as the spawner places things."
              >
                All layouts
              </div>
              <div style={{ marginBottom: 4 }}>
                {refKinds.map((k) => {
                  const on = visibleKinds === null || visibleKinds.includes(k);
                  const color =
                    k === 'key' ? '#ffd166' : k === 'enemy spawn' ? '#f87171' : '#9aa';
                  return (
                    <button
                      key={k}
                      onClick={() =>
                        setVisibleKinds(
                          visibleKinds === null
                            ? [...kinds, ...refKinds].filter((x) => x !== k)
                            : on
                              ? visibleKinds.filter((x) => x !== k)
                              : [...visibleKinds, k],
                        )
                      }
                      style={{
                        ...chipStyle(on),
                        background: on ? '#1a1a2e' : '#0f0f1e',
                        color: on ? color : '#555',
                        border: '1px dashed #3a3a5a',
                      }}
                      title={
                        k === 'enemy spawn'
                          ? "The wave's spawn slots — every layout fights from the same slots."
                          : k === 'key'
                            ? 'Authored key slots — keys exist in every layout (psz-godot scatters/places them by rule, not from this table).'
                            : 'Measured in the original but not placed by psz-godot.'
                      }
                    >
                      {k} {refByKind[k]}
                    </button>
                  );
                })}
              </div>
            </>
          )}

          {entry.groups == null ? (
            <div style={{ fontSize: 11, color: '#8a90b8' }}>
              No recoverable group table — the original builds this file flat,
              so it has no variations to preview.
            </div>
          ) : (
            <>
              <div
                style={sectionLabel}
                title="A room never builds every record at once. One of five layout masks picks which of groups 0–4 are built verbatim (drawn against a weight row by the room's tree depth); group 5 — traps — rolls a separate 0–3 count at 40/20/20/20. A mask is only eligible if every group it names is non-empty. The share quoted per row is the 4–6 depth band; layout 4 is never drawn by design (the original's draw returns 0..3)."
              >
                Layouts
              </div>
              <div style={{ marginBottom: 6 }}>
                {masks.map((m, i) => {
                  const on = eligible[i] || sharesByBand.some((s) => (s[i] ?? 0) > 0);
                  const selected = layoutMask === m;
                  const built = maskGroups(m);
                  const shares = sharesByBand.map((s) => s[i] ?? 0);
                  const never = i === 4;
                  const title = !on
                    ? `mask ${m} names an empty group for this room — never drawn`
                    : never
                      ? `mask ${m} → groups ${built.join(', ')} + the trap roll. Never drawn: the original's layout draw returns 0..3 by design — group 4's objects never spawn in a free field.`
                      : `mask ${m} → groups ${built.join(', ')} + the trap roll · draw % by depth <4 / 4–6 / ≥7: ${shares.join(' / ')}`;
                  return (
                    <label
                      key={m}
                      title={title}
                      style={{
                        display: 'flex',
                        alignItems: 'center',
                        gap: 8,
                        padding: '6px 8px',
                        borderRadius: 6,
                        marginBottom: 2,
                        background: selected ? '#2a2a4a' : 'transparent',
                        opacity: on ? 1 : 0.45,
                        cursor: on ? 'pointer' : 'not-allowed',
                      }}
                    >
                      <input
                        type="radio"
                        name="authored-layout"
                        checked={selected}
                        disabled={!on}
                        onChange={() => setLayoutMask(m)}
                        style={{ accentColor: '#4a9eff', margin: 0 }}
                      />
                      <span>L{i}</span>
                      <span style={{ color: '#8a90b8' }}>
                        groups {built.join(', ')} + traps
                      </span>
                      <span style={{ marginLeft: 'auto', color: on && !never ? '#8a90b8' : '#555' }}>
                        {on && !never ? `${faceShares[i]}%` : '—'}
                      </span>
                    </label>
                  );
                })}
              </div>
              {group5Total > 0 && (
                <div style={{ marginBottom: 6 }}>
                  <span
                    style={{ fontSize: 11, color: '#8a90b8', marginRight: 4 }}
                    title="Group 5 is rolled per visit: rand(100) against 40/20/20/20 gives a count of 0–3, the group is shuffled, that many are taken. Which N varies per visit — the preview takes the first N in table order."
                  >
                    trap roll:
                  </span>
                  {Array.from({ length: Math.min(3, group5Total) + 1 }, (_, n) => (
                    <button
                      key={n}
                      onClick={() => setGroup5Count(n)}
                      style={chipStyle(group5Count === n)}
                      title={`rolled count ${n}${group5Weights[n] !== undefined ? ` — ${group5Weights[n]}% of visits` : ''}`}
                    >
                      {n}
                    </button>
                  ))}
                </div>
              )}
            </>
          )}

          <div
            style={sectionLabel}
            title="Toggle kinds in the viewport. Kinds with an identified model render as that model (streamed from the asset CDN; a failed load renders its marker in red) — boxes and walls in this field's own art; kinds with no identified model (the elemental trap families) draw as discs, in the colour of their button."
          >
            Kinds
          </div>
          <div style={{ marginBottom: 8 }}>
            <button onClick={() => setVisibleKinds(null)} style={chipStyle(visibleKinds === null)}>
              show all
            </button>
            {kinds.map((k) => {
              const on = visibleKinds === null || visibleKinds.includes(k);
              return (
                <button
                  key={k}
                  onClick={() =>
                    setVisibleKinds(
                      visibleKinds === null
                        ? kinds.filter((x) => x !== k)
                        : on
                          ? visibleKinds.filter((x) => x !== k)
                          : [...visibleKinds, k],
                    )
                  }
                  style={{
                    ...chipStyle(on, KIND_COLOR[k]),
                    color: on ? KIND_COLOR[k] ?? '#e8e8f0' : '#555',
                    borderColor: on ? KIND_COLOR[k] ?? '#2a2a4a' : '#2a2a4a',
                  }}
                >
                  {k} {byKind[k]}
                </button>
              );
            })}
          </div>

        </>
      )}
    </div>
  );
}
