/**
 * Data validation for data/enemy_attacks.json (spec /mechanics/enemy-attacks).
 * Generated by scripts/tools/gen_enemy_attacks.py, hand-tuned in #/enemy-room.
 */
import { describe, it, expect } from 'vitest';
import fs from 'fs';
import path from 'path';

const ATTACKS_PATH = path.resolve(__dirname, '../../public/data/enemy_attacks.json');
const ENEMIES_PATH = path.resolve(__dirname, '../../public/data/enemies.json');

const config = JSON.parse(fs.readFileSync(ATTACKS_PATH, 'utf-8'));
const roster: Array<{ id: string }> = JSON.parse(fs.readFileSync(ENEMIES_PATH, 'utf-8'));
const rosterIds = new Set(roster.map((e) => e.id));
const entries: Array<[string, any]> = Object.entries(config.enemies);

describe('enemy_attacks.json — structure', () => {
  it('has schema_version 1 and defaults blocks', () => {
    expect(config.schema_version).toBe(1);
    expect(config.defaults.fsm.attack_fallback_duration).toBeGreaterThan(0);
    expect(config.defaults.attack.windup_frac).toBeLessThan(config.defaults.attack.damage_end_frac);
  });

  it('covers every roster enemy (ids keyed to data/enemies/*.tres)', () => {
    // enemy_attacks.json is seeded from data/enemies/*.tres, which is a
    // superset of enemies.json (the .tres registry gained entries the
    // hand-maintained list hasn't caught up on). Every roster id must be
    // covered; extras are listed here so drift stays visible.
    const missing = [...rosterIds].filter((id) => !config.enemies[id]);
    expect(missing, `roster enemies missing from enemy_attacks.json: ${missing.join(', ')}`).toHaveLength(0);
    const extras = entries.map(([id]) => id).filter((id) => !rosterIds.has(id));
    if (extras.length > 0) {
      // Known drift between the two rosters — keep it visible, not fatal.
      console.warn(`enemy_attacks.json ids not in enemies.json: ${extras.join(', ')}`);
    }
  });
});

describe('enemy_attacks.json — per-enemy invariants', () => {
  it('every enemy has stats and ≥1 attack', () => {
    const bad = entries.filter(
      ([, e]) => !e.stats || !Array.isArray(e.attacks) || e.attacks.length === 0,
    );
    expect(bad.map(([id]) => id), 'enemies without stats or attacks').toHaveLength(0);
  });

  it('attack timeline fractions are ordered: 0 ≤ windup_frac < damage_end_frac ≤ 1', () => {
    const bad: string[] = [];
    for (const [id, e] of entries) {
      for (const a of e.attacks) {
        const w = a.windup_frac ?? config.defaults.attack.windup_frac;
        const d = a.damage_end_frac ?? config.defaults.attack.damage_end_frac;
        if (!(w >= 0 && w < d && d <= 1)) bad.push(`${id}/${a.id}`);
      }
    }
    expect(bad, `attacks with bad timeline fractions: ${bad.join(', ')}`).toHaveLength(0);
  });

  it('range bands, weights, reach, and angles are sane', () => {
    const bad: string[] = [];
    for (const [id, e] of entries) {
      for (const a of e.attacks) {
        const min = a.min_range ?? config.defaults.attack.min_range;
        const max = a.max_range ?? config.defaults.attack.max_range;
        const weight = a.weight ?? config.defaults.attack.weight;
        const reach = a.hit_reach ?? config.defaults.attack.hit_reach;
        const angle = a.hit_half_angle_deg ?? config.defaults.attack.hit_half_angle_deg;
        if (!(min >= 0 && min < max)) bad.push(`${id}/${a.id} range`);
        if (!(weight > 0)) bad.push(`${id}/${a.id} weight`);
        if (!(reach > 0)) bad.push(`${id}/${a.id} reach`);
        if (!(angle > 0 && angle <= 180)) bad.push(`${id}/${a.id} angle`);
      }
    }
    expect(bad, `attacks with bad geometry: ${bad.join(', ')}`).toHaveLength(0);
  });

  it('attack ids are unique per enemy and clips are non-empty tokens', () => {
    const bad: string[] = [];
    for (const [id, e] of entries) {
      const seen = new Set<string>();
      for (const a of e.attacks) {
        if (!a.id || seen.has(a.id)) bad.push(`${id}/${a.id ?? '?'} dup-or-empty id`);
        seen.add(a.id);
        if (typeof a.clip !== 'string' || a.clip.length === 0) bad.push(`${id}/${a.id} clip`);
      }
    }
    expect(bad, bad.join(', ')).toHaveLength(0);
  });
});
